name: Documentation Issue
description: Report an issue with documentation or request documentation improvements
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! Please fill out this form with details about the documentation issue.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear explanation
        - Broken links
        - Code examples not working
        - API reference issues
        - Tutorial/guide improvements
        - Typo/grammar
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: "e.g., README.md, docs/api-reference.md, line 42"
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? (copy/paste the relevant section)
      render: markdown

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the specific issue with the current documentation
      placeholder: What's wrong, missing, or unclear about the current documentation?
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: Provide specific suggestions for improvement
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What were you trying to do when you encountered this documentation issue?
      placeholder: Describe what you were trying to accomplish

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Which audience would benefit most from this documentation improvement?
      multiple: true
      options:
        - New users getting started
        - Existing users learning advanced features
        - Developers integrating the SDK
        - Contributors to the project
        - All users

  - type: dropdown
    id: platform-specific
    attributes:
      label: Platform Specific
      description: Is this documentation issue specific to certain platforms?
      multiple: true
      options:
        - WhatsApp
        - Messenger
        - Instagram
        - All platforms
        - Not platform-specific

  - type: textarea
    id: proposed-content
    attributes:
      label: Proposed Content
      description: If you have specific content suggestions, please provide them here
      render: markdown
      placeholder: |
        Provide your suggested documentation content here.
        This could include:
        - Corrected text
        - New examples
        - Additional explanations
        - Code samples

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to fix this documentation issue?
      options:
        - label: I would be willing to submit a PR to fix this documentation issue
        - label: I would be willing to help review documentation changes

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this documentation issue hasn't been reported before
          required: true
        - label: I have provided specific details about the location and nature of the issue
          required: true
        - label: I have suggested specific improvements where possible
          required: true